### ISSUE TITLE
Product regional availability

### ISSUE THREAD

**Issue by PatMyron** [GoogleCloudPlatform/region-picker#10]
I've been doing similar research @ https://github.com/PatMyron/cloud and a lot of times feature availability can be the most important factor in cloud region selection

**Comment by PatMyron** [comment]
While I've been scraping the charts in https://cloud.google.com/about/locations/, it'd be much easier for others if aggregated data was added to this

**Comment by steren** [comment]
I'd like to add this feature, but unfortunately, I am not aware of a machine readable dataset of product availability. Let me know if you find something

**Comment by steren** [comment]
One option could be to implement a JS parser tailored at parsing https://cloud.google.com/about/locations/ (the same way we have a parser for the carbon data csv)

The page structure is an HTML table, and it's probably safe to assume that it will stay an HTML table over time. So if we rely only on basic HTML table markup. It should be pretty solid.

We would then need to save a snapshot of this page and serve it under the same domain as the tool.

**Comment by steren** [comment]
We could copy the html of that page and then use a technique like that https://gomakethings.com/getting-html-with-fetch-in-vanilla-js/
