### ISSUE TITLE
Save Countries Selected and add to output

### ISSUE THREAD

**Issue by intotecho** [GoogleCloudPlatform/region-picker#13]
The `where is your traffic coming from` drop down is too small. 
There may be better UI widgets for a multiselect list.
Once a country is selected, it should be added to the output. 
The site should produce a report that engineers can submit to the greater powers to backup their recommendation or decision. 

Maybe add another parameter for features only supported in some regions, like vertex-ai managed notebooks for one example, or certain CPU or GPU types. Without getting too complex. 

If the user clicks "I need Vertex-AI managed notebooks" then those regions could be filtered out of the result.

**Comment by steren** [comment]
Closing, because these 2 feature requests are already tracked

**Comment by steren** [comment]
https://github.com/GoogleCloudPlatform/region-picker/issues/10

**Comment by steren** [comment]
https://github.com/GoogleCloudPlatform/region-picker/issues/3
