### ISSUE TITLE
Hong Kong region (asia-east2) not showing as top pick for traffic coming from Hong Kong

### ISSUE THREAD

**Issue by LiQuBit** [GoogleCloudPlatform/region-picker#16]
Hi, I was trying to put latency as the only decision factor and specifying traffic coming from Hong Kong, it is strange that the Hong Kong region (asia-east2) doesn't show up as the top choice. In fact, it doesn't even appear among the top 6 choices.

**Comment by steren** [comment]
Thanks for the report! Great find.

I confirm that there is a problem when the lat/long of the region corresponds exactly to the lat/long of the country selected. 

the distance_normalized attribute isn't properly computed.

I will send a fix
