### ISSUE TITLE
add me-central2 region

### ISSUE THREAD

**Issue by IOAI** [GoogleCloudPlatform/region-picker#22]
lowest latency region for saudi arabia should be me-central2 (Dammam) but it is currently showing a different region. is it possible to add all new locations in middle east to the list?

**Comment by steren** [comment]
Until https://github.com/GoogleCloudPlatform/region-picker/issues/19 is fixed, new regions are only added when carbon data is available

**Comment by steren** [comment]
me-central2 added, with missing carbon data
