### ISSUE TITLE
Some high carbon regions have 3 leaves

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/region-picker#6]
Leaf rendering seems to have an issue: Jakarta shouldn't have 3 leaves.

It doesn't seem to affect the region sorting. The problem likely comes from the code that translates carbon info into number of leaves

![image](https://user-images.githubusercontent.com/360895/126847689-ed29dad5-92e6-4fb2-a872-1f4e3f8e4935.png)

**Comment by steren** [comment]
Bug is because https://github.com/GoogleCloudPlatform/region-picker/blob/main/index.js#L131 doesn't handle regions with gCO2_kWh > 600. The code should return 0

**Comment by QizorQ8** [comment]
> Leaf rendering seems to have an issue: Jakarta shouldn't have 3 leaves.
> 
> It doesn't seem to affect the region sorting. The problem likely comes from the code that translates carbon info into number of leaves
> 
> ![image](https://user-images.githubusercontent.com/360895/126847689-ed29dad5-92e6-4fb2-a872-1f4e3f8e4935.png)
