### ISSUE TITLE
Carbon footprint rating

### ISSUE THREAD

**Issue by pierre-tabet** [GoogleCloudPlatform/region-picker#9]
If I filter the regions with 100% Lower carbon footprint, 0% Lower price and 0%Lower latency. It ranks regions only using Carbon Free Energy percentages. Surely this is incorrect because when a region is not using carbon free energy it should take into account the Grid carbon intensity too. For example:
us-central1 has a Carbon Free Energy: 93% and a Grid carbon intensity: 454 gCO2eq/kWh. This means 7% of the time it uses 454 gCO2eq/kWh, and on average it is 0.07* 454 = 31.78gCO2eq/kWh.

us-west1 has a Carbon Free Energy: 90% and a Grid carbon intensity: 78 gCO2eq/kWh. This means 10% of the time it uses 78 gCO2eq/kWh, and on average it is 0.10* 78 = 7.8gCO2eq/kWh.

Yet us-central1 is showing up better on the Lower carbon footprint ranking than the us-west1.

<img width="1444" alt="Screenshot 2022-04-26 at 16 50 11" src="https://user-images.githubusercontent.com/60051148/165328204-05f1316a-49f2-4388-8920-9c272079937d.png">

**Comment by steren** [comment]
I agree that the two carbon attributes could be better blended together. Today, the logic is that CFE% is used if present, otherwise fallback to carbon intensity.

**Comment by steren** [comment]
We are now always computing the CFE% for every region, so this issue, which was due to the logic using grid intensity when CFE isn't available, shouldn't occur anymore
